### ISSUE TITLE
Access-Control-Allow-Origin -> *

### ISSUE THREAD

**Issue by Wei-1** [Orabig/codingame-api-rfc#1]
I will like to propose to change the API setting with
{'Access-Control-Allow-Origin', '*'}
so that people can access it with clientside JQuery with a static website.

**Comment by Orabig** [comment]
(EDIT : I thought this comment was about another project with an API handled by me :) )
You should tell that to Codingame guys ;)

**Comment by Wei-1** [comment]
Yeah...
I just asked Thibaud.
They don't want to change the API setting because of security concern.
We can close this issue.
