### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by BenjaminUrquhart** [Orabig/codingame-api-rfc#3]
Is this repo still being maintained? I've reversed quite a number of routes that I'd like to document in a centralized place (see: https://github.com/BenjaminUrquhart/CodinGame-Bot/blob/master/src/net/benjaminurquhart/codinbot/api/enums/Route.java).

**Comment by Orabig** [comment]
Yes ! I did not work on the subject for a while, but I'd be happy to accept PR and update and gather these informations for anyone

**Comment by BenjaminUrquhart** [comment]
Ok, thanks
